name: CI

on:
  push:
    branches:
      - '**'

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Restore Gradle Build Cache
        uses: actions/cache/restore@v3
        with:
          path: ./build-cache
          key: gradle-build-cache

      - name: Build
        run: ./gradlew build -x bootJar -x check

      - name: Test
        run: ./gradlew test

      - name: Build and publish Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: ./gradlew bootBuildImage --publishImage

      - name: Save Gradle Build Cache
        uses: actions/cache/save@v3
        if: always()
        with:
          path: ./build-cache
          key: gradle-build-cache
